### ISSUE TITLE
Add scope support to authorization_details?

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#27]
Shall we add the possibility to carry scope values as top level elements in the authorization details (in the same way as XYZ)? Having worked on wording re scope vs authorization details it seems a pretty obvious migration path. 

@jricher 
@b---c 
@panva 
What do you think?

**Comment by jricher** [comment]
It works in XYZ because the top level is a multi-type JSON model, where something can be either an object or string. This is common throughout that protocol (it's just the "handle" mechanism), but I fear it'd be too much for implementors of OAuth to wrap around. Plus then we'd need rules for what to do with "internal" scope values vs. values in the `scope` parameter. Which take precedence, or are they always merged together?

**Comment by b---c** [comment]
My initial inclination is that it's not something that should be added.

**Comment by tlodderstedt** [comment]
wfm
