### ISSUE TITLE
Valid characters for type

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauthstuff/draft-oauth-rar#28]
Do you have any plan to put restrictions on characters for the `type` field?

Because `authorization_data_types` and `authorization_data_types_supported` metadata are defined and the spec states _"The AS MUST refuse to process any unknown authorization data type"_, AS implementations have to check values of `type` fields.

From an implementer's point of view, important points are as follows.

1. Whether to allow non-ASCII letters? (any Unicode characters such as 🐉⚡️🥓?)
2. Whether to allow white spaces?

If these points are not mentioned in the spec explicitly, it is likely that we would encounter incompatibilities among implementations.

Actually, examples of `type` in the current spec are as follows:

- `payment_initiation`
- `account_information`
- `https://scheme.example.org/files`
- `https://www.someorg.com/payment_initiation`
- `https://scheme.example.org/storage`

but I was told that `type` may contain spaces like "`payment information`" and the implementation should take it into account. However, it is difficult for implementers to notice the possibility, especially because all the examples don't include white spaces.

FYI: `scope` in RFC 6749 is defined as follows:

    scope       = scope-token *( SP scope-token )
    scope-token = 1*NQCHAR

and `NQCHAR` is defined as follows:

    NQCHAR     = %x21 / %x23-5B / %x5D-7E

`%x20` (space), `%x22` (double quotation mark) and `%x5C` (backslash) are not included in `NQCHAR`.

**Comment by jricher** [comment]
On top of this, we will need to be clear about what the comparison process is, since this field is used to to switch functionality with the rest of structure. 

From my perspective, since this field is always encoded as a single JSON string, I think anything that is allowed as a JSON string should be allowed as a value for this field. https://tools.ietf.org/html/rfc8259#section-7

**Comment by TakahikoKawasaki** [comment]
[Unicode normalization](https://unicode.org/reports/tr15/) is tough.

&#x3067; = [U+3067](https://www.compart.com/en/unicode/U+3067)
&#x3066;&#x3099; = [U+3066](https://www.compart.com/en/unicode/U+3066) + [U+3099](https://www.compart.com/en/unicode/U+3099)

If `type` is used for switching, all the more some restrictions should be put on characters for `type`.

**Comment by jricher** [comment]
We aren't looking at end-user-facing strings or processing user input in this field though. These values are going to be statically defined by the API owners as the resource request "type", which is going to have a lot of additional information about what the type means in terms of other fields being included. As long as we define comparison to be against the exact bytes of the string (which needs to be added to the spec, admittedly), I don't see any of the issues above coming into play. 

I don't think we should do any unicode normalization. I don't think it should have any way to know that U+FA11 and 5+5D0E are equivalent in any meaningful way, or that the two examples in your comment "look" the same to a person. These are different byte strings and should be different for our comparison purposes. 

I think we can do all of that without any character restriction on the field because an implementation is going to take the JSON string out of the JSON parser and do the comparison based on that string of unicode bytes.
