### ISSUE TITLE
Authorization request with both authorization_details and resources

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauthstuff/draft-oauth-rar#40]
The example in "2.3. Relationship to "resource" parameter" includes

1. An authorization request with `authorization_details` and without `resource`.
2. A token request with `resource`.

This filters elements in `authorization_details` by the `resource`.

I want to know the expected behavior when an authorization request comes with both `authorization_details` and `resource`s.

Should it be treated as if elements whose `locations` don't include any one of `resource`s specified by the authorization request didn't exist from the beginning? Or, shouldn't `resource`s in the authorization request affect `authorization_details`? Note that the latter still has a meaning because the `resource`s are used as the values of audience (`aud`).

**Comment by TakahikoKawasaki** [comment]
Hmm. The second paragraph of Section 2.3 says as follows.

>If a client uses `authorization_details` with `locations` elements and the `resource` parameter in the same authorization request, the `locations` data take precedence over the data conveyed in the `resource` parameter for that particular authorization details object.

It sounds to me that the conclusion brought by this paragraph will be **_"if `authorization_details` contains `locations`, `resource` parameters in the same authorization request should be ignored."_**

Is this what is intended? I'm sorry I don't understand what the paragraph wants to achieve.

**Comment by TakahikoKawasaki** [comment]
Regarding the `resource` parameter which is defined in [Resource Indicators for OAuth 2.0](https://datatracker.ietf.org/doc/draft-ietf-oauth-resource-indicators/?include_text=1):

The `resource` parameters in an authorization request will be
- used as the elements of the `aud` claim of the access token issued from the authorization endpoint, and
- associated with the authorization code issued from the authorization endpoint, and thus used as the default set of the elements of the `aud` claim of the access token which will be issued from the token endpoint later.

The `resource` parameters in a token request will be
- used as the elements of the `aud` claim of the access token issued from the token endpoint if the preceding authorization request has included no `resource` parameters, otherwise,
- used to filter the resources associated with the authorization code, and the final elements of the `aud` claims of the access token issued from the token endpoint will be the intersection of (a) resources in the authorization request and (b) the resources in the token request.

IMHO, to avoid confusing developers who use the `resource` parameter, the behaviors of the `resource` parameter described above should not be affected by `locations` in the `authorization_details` parameter.

However, it seems to me that the second paragraph of the section 2.3 of RAR is trying to change the meaning given by the `resource` parameters in an authorization request. Possible interpretations would be, for example, (a) the `resource` parameters should be ignored, (b) (merged?) `locations` should be used as the elements of the `aud` claim of the access token issued from the authorization endpoint as if the locations were specified as resources, ...

**Comment by TakahikoKawasaki** [comment]
Filtering elements in the `authorization_details` array by the `resource` parameters might be okay, but making `locations` take precedence over the `resource` parameters will confuse developers. At least, in the current draft, the relationship between `locations` and `resource` at the authorization endpoint and that at the token endpoint are different. This is not good.

If the `resource` parameters are used to filter elements in the `authorization_details` array (regardless of whether it is done at the token endpoint and/or at the authorization endpoint). The corollary would be:

_"When the `resource` parameters are used with the `authorization_details` parameter, in typical cases, the authorization request or the token request will have to list locations duplicately as resources in order to prevent elements in the `authorization_details` array from being filtered out. Also, all the elements in the `authorization_details` array will have to have `locations` to avoid being filtered out."_

Developers who want to use the `resource` parameter to set the `aud` claim of access tokens will find that they **cannot use the `resource` parameter casually with the `authorization_details` parameter due to the side effect described in the section 2.3 of the RAR spec**.

The simplest solution would be just dropping the section 2.3 (Relationship to "resource" parameter) from the RAR spec. If we want a mechanism to filter elements in the `authorization_details` array at the token endpoint (and at the authorization endpoint), a safer approach would be to define a new request parameter such as `authorization_details_filter`, which may possibly have a complex JSON structure like the one defined in "[5. Requesting Verified Claims](https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html#rfc.section.5)" in [OpenID Connect for Identity Assurance 1.0](https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html).

**Comment by tlodderstedt** [comment]
I think the word "filter" caused a misconception. What I want to achieve is proper support for RS/audience specific access tokens.

Using a certain "resource" at the tokens endpoint indicates the RS/aud/location a client is going to use an access token. Using the "resource" value and the "locations" elements to select the authorization_details applicable/relevant for a certain RS is the way the current draft suggests. So this is not arbitrary filtering but minting audience specific access tokens.

**Comment by TakahikoKawasaki** [comment]
Audience restriction is achieved by the `resource` parameter ([Resource Indicators for OAuth 2.0](https://datatracker.ietf.org/doc/draft-ietf-oauth-resource-indicators/?include_text=1)). We should let `resource` focus on controlling `aud`. If we want to put restrictions on locations, if you don't like the word "filter", how about defining a new request parameter, `location`?

**Comment by tlodderstedt** [comment]
Just putting the "resource" value in the "aud" claim of an access token is not what I mean with audience restriction. 

A true audience restricted access token (or better put RS-specific access token) should also only contain the data this RS requires to see. With (Resource Indicators for OAuth 2.0) the AS must put the full scope into an access token because there is no clear definition of the relationship between RS and scope values. 

This changes with authorization_details. Now we can add the authorization data relevant for a certain RS to the access token. The account information service only sees the authorization_details for account information and the payment service sees the authorization_details for payments, ....

**Comment by TakahikoKawasaki** [comment]
It sounds that, rather, you want to make the very `resource` parameter work in the context of `authorization_details`. Okay, but then, please keep in mind the following corollary I described above.

> _"When the `resource` parameters are used with the `authorization_details` parameter, in typical cases, the authorization request or the token request will have to list locations duplicately as resources in order to prevent elements in the `authorization_details` array from being filtered out. Also, all the elements in the `authorization_details` array will have to have locations to avoid being filtered out."_

This means that **implementations will drop all elements without `locations` in the `authorization_details` array whenever `resource` parameters are used**.

Also, still, I think the second paragraph of the section 2.3 should be modified. The current description breaks the expected behavior of the `resource` parameters in an authorization request.

**Comment by tlodderstedt** [comment]
It seems we are looking from different angles onto this topic. In order to reach common ground I suggest we start the discussion from scratch.

### What do I want to achieve? 

Resource indicators assigns access tokens to certain RSs but leaves the assignment of scope values somewhat open/at the discretion of the AS. It especially does not give a client a way to specify "I want scope X at RS A (and nowhere else)". That's what RAR can be used for since 
RAR allows to allocate authorization_details to access tokens for certain RS(s) by using the "locations" element. This together with strong typing prevents ambiguity (one cause of vulnerabilities) and gives flexibility (e.g. authorization_details of the same type at different RSs in the same transaction).

I envision "resource" and "authorization_details" to work as follows: The client specifies its authorization requirements (including allocation to RSs) in the authorization request using "authorization_details" only since "authorization_details" is more expressive than resource. In the token request, the client will typically ask for an access token for a certain RS (see https://tools.ietf.org/html/draft-ietf-oauth-security-topics-13#section-3.3). Using "resource" to specify this RS is the simplest way to achieve this. 

I wrote the spec text along those ideas. I have to admit I did not fully consider backward compatibility with resource indicators. So here are my thoughts how we could improve the spec:

### Authorization Request

If "authorization_details" and "resource" are present in the same authorization request, I see the following cases:
* there are "authorization_details" w/o locations -> treat those authorization details as if they had locations elements containing the "resource" values
*  there are "authorization_details"  w/ locations - (a) EITHER use locations of particular "authorization_details" only (since it is more specific) OR (b) add resource values as locations OR (c) overwrite all locations with the resource values

I'm leaning towards (a).

The result of this processing is a combined internal representation of authorization details taking into considerations resource parameter values that is part of the authorization grant (and refresh token). 

### Token Request

Assumption: "resource" parameter is present (no "authorization_details" parameter is present) 

* set "aud" to "resource" values
* If there was neither a "resource" parameter nor "authorization_details" w/ locations present in the authorization request -> add all authorization details to access token
* else -> add only authorization details to access token that have a matching location (might also be automatically added locations if we go for (b) or (c) for the authorization request)

Thoughts?

**Comment by TakahikoKawasaki** [comment]
> - Authorization Endpoint: there are "authorization_details" w/o locations -> treat those authorization details as if they had locations elements containing the "resource" values
> - Token Endpoint: If there was neither a "resource" parameter nor "authorization_details" w/ locations present in the authorization request -> add all authorization details to access token

I'm afraid these rules will easily cause implementation bugs.

**Comment by tlodderstedt** [comment]
I'm surprised. Those rules describe exactly the behavior I would expect an AS to implement for resource + scope. 
But anyway, if you have any ideas in mind how to simplify the definition please describe it.

**Comment by TakahikoKawasaki** [comment]
Sorry for having surprised you. I should have described my concerns in detail.

**_"Authorization Endpoint: there are "authorization_details" w/o locations -> treat those authorization details  as if they had locations ..."_** (1) requires a special `if-else` branch in implementations where `resource`s don't affect `authorization_details` if none of elements in `authorization_details` has `locations` but affects `authorization_details` once any one of elements has `locations` (which will surely require **nonintuitive** coding) and (2) may bring different interpretations where some implementations may insert the resources as `locations` into the original `authorization_details` and others may don't touch the original `authorization_details`.

**_"Token Endpoint: If there was neither a "resource" parameter nor "authorization_details" w/ locations present in the authorization request"_** is complex as conditions.

**For consistency**, when `authorization_details` and `resource`s are given in an authorization request, elements in `authorization_details` that don't have `locations` should be dropped, implying that all elements in `authorization_details` should have `locations` when `resource` request parameters are used. My concerns are brought by the inconsistency between the behavior of `resource` at the authorization endpoint and that at the token endpoint. The inconsistency will easily cause implementation bugs and/or wrong interpretations.

**Comment by tlodderstedt** [comment]
It seems I expressed my proposal not precisely enough. 

> (1) requires a special if-else branch in implementations where resources don't affect authorization_details if none of elements in authorization_details has locations but affects authorization_details once any one of elements has locations (which will surely require nonintuitive coding)

I certainly do not intend to let the behavior switch that way. Here is modified text:

* **For all** "authorization_details" w/o locations -> treat those authorization details as if they had locations elements containing the "resource" values
* **For all** "authorization_details" w/ locations - (a) EITHER use locations of particular "authorization_details" only (since it is more specific) OR (b) add resource values as locations OR (c) overwrite all locations with the resource values

> (2) may bring different interpretations where some implementations may insert the resources as locations into the original authorization_details and others may don't touch the original authorization_details.

Well, I first of all wanted to be as specific as possible in my proposal. And (virtually) adding the resource to the locations elements read reasonable to me. I was merely thinking about a possible internal representation at the AS and how this internal representation is used by the AS to process token requests. I think that’s especially useful for discussing the different options. I'm still waiting for your feedback on options a-c. (a) does not require the augmented internal representation, so this should be your natural choice, I guess.

> For consistency, when authorization_details and resources are given in an authorization request, elements in authorization_details that don't have locations should be dropped, implying that all elements in authorization_details should have locations when resource request parameters are used. 

Your proposal makes locations in conjunction with resource mandatory. But of locations needs to be used anyway, using resource makes no longer sense since everything resource can carry can be expressed in locations. 

Why should we do that?

> My concerns are brought by the inconsistency between the behavior of resource at the authorization endpoint and that at the token endpoint. The inconsistency will easily cause implementation bugs and/or wrong interpretations.

That's difference in behavior for the different use cases not inconsistency. The authorisation request describes the maximum extend of the grant the client is asking for. Using the resource parameter to define the places authorization_details are effective at is a nice short cut for constructing richer authorization details. The token request produces concrete access tokens based on the grant approved by the resource owner. Using the resource parameter to narrow the respective token down to a certain RS is very useful. 

This behavior is compatible with the way resource and scope interact with each other (or at least could according to the resource indicator spec). resource in the authorization request adds the possible target RSs (for all scope values) to the grant and resource in the token request (may) be limited to the resources specified in the authorization request and the scope values assigned to the access token may be narrowed to the scope values applicable to a certain RS.

See https://tools.ietf.org/html/draft-ietf-oauth-resource-indicators-08#section-2.2 paragraphs 2 and 3. 

The alternative is to make resource and authorization_details mutual exclusive but I think this is even more difficult to understand.

**Comment by TakahikoKawasaki** [comment]
@tlodderstedt It was great we could have a face-to-face meeting yesterday. I think I now understand the behavior you expect. I'm thinking of writing a pseudo code to make sure we have the same understanding.

**Comment by TakahikoKawasaki** [comment]
@tlodderstedt How about this pseudo code?

```java
private static AuthzDetailsElement[] filterElementsByResources(
        AuthzDetailsElement[] elements, URI[] resources)
{
    // If the request does not include the 'resource' request parameters.
    if (resources == null || resources.length == 0)
    {
        // Filtering is not performed. All the elements included in the
        // 'authorization_details' array are used without being dropped.
        return elements;
    }

    // The resultant set of elements after filtering.
    List<AuthzDetailsElement> filteredElements
        = new ArrayList<AuthzDetailsElement>();

    // For each element listed in the 'authorization_details' array.
    for (AuthzDetailsElement element : elements)
    {
        // The "locations" property in the element.
        String[] locations = element.getLocations();

        // If the element does not have the "locations" property.
        if (locations == null)
        {
            // In this case, the element is selected unconditionally.
            filteredElements.add(element);
            continue;
        }

        // If the set of resources covers any one of the locations.
        if (doResourcesCoverAnyLocation(resources, locations))
        {
            // In this case, the element is selected.
            filteredElements.add(element);
            continue;
        }

        // The element has the "locations" property, but none of the
        // locations is not covered by the set of resources. In this
        // case, the element is dropped.
    }

    // Convert the list of filtered elements to an array.
    return filteredElements.toArray(
            new AuthzDetailsElement[filteredElements.size()]);
}


private static boolean doResourcesCoverAnyLocation(
        URI[] resources, String[] locations)
{
    // For each resource that corresponds to a 'resource' parameter.
    for (URI resource : resources)
    {
        // For each location in the "locations" property.
        for (String location : locations)
        {
            // If the resource covers the location.
            if (doesResourceCoverLocation(resource, location))
            {
                return true;
            }
        }
    }

    // None of the locations is covered by the set of resources.
    return false;
}


private static boolean doesResourceCoverLocation(URI resource, String location)
{
    // NOTE: The logic here is implementation-dependent
    //       unless the specification defines rules.
}
```

**Comment by tlodderstedt** [comment]
@TakahikoKawasaki thanks a lot for writing down the code. 

Your code seems to implement the following semantics:

- For all "authorization_details" w/o locations -> treat them as applicable to all resources, i.e. add them to the result set independent of the resource value
- For all "authorization_details" w/ locations -> add only those authorization_details objects with at least one location matching the resource value.

That semantics works well for me. 

I will try to come up with a proposal for the "doesResourceCoverLocation" logic.

**Comment by tlodderstedt** [comment]
@TakahikoKawasaki  took quite some time, but here is the PR #60 

Please review (I sent you an invite).
