### ISSUE TITLE
version field

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#42]
Vladimir suggested to add a "version" field to the authorization data in order to explicitly represent versions of authz data types and allow ASs to migrate existing authorization details objects (retained as part of the respective grant) automatically.

**Comment by jricher** [comment]
I don't like this idea. Versioning should be handled with the "type" field itself and not a combination of two things. So I can have `foo` and then `foo2`.

**Comment by b---c** [comment]
tend to agree w/ @jricher here

**Comment by vdzhuvinov** [comment]
When we looked at the RAR we realised that applications can go crazy with the authZ details objects and where you have complexity things also tend to change, in small or not so small ways.

With RAR, as with scope and claims, we want to allow consent to be persisted. The question came up what to do when we have persisted consent for thousands or millions of users and the schema for a "type" changes in some slight way? We can ask them to re-consent, or we could give the app developers the choice to specify a "transform" from the old to the new JSON schema for the type. We have done such JSON transformations in the past with APIs, where the older version was dynamically simulated via the transformation, i.e. there was no real old logic underneath.

In order to handle such transformations the types will need to be versioned in some way. The version can indeed be encoded into the "type", e.g. as `foo2` or `foo_v2`, but it's not obvious to a non-human how it can then be reliably extracted from the field, to get the tuple `foo`, `2`. Two possible solutions are to expect the version to be encoded in a canonic form, or to allow app developers to configure a regexp to extract the version from the type field. A third solution is to simply put the version into its own top-level field. Did you have a chance to look at the problem of versioning from this perspective?

Encoding the version into the type also has implications for AS and client metadata. If the version is encoded into the type it will be clear what type versions the AS supports. Clients that are strictly checked however will need to update their registration if they want to use a newer version, or an older version is no longer supported.

Do you have thoughts or comments on encoding the version into the type in some canonical way?

**Comment by tlodderstedt** [comment]
Your last statement about server metadata makes me thinking encoding of the version into the type is beneficially. First of all, advertising support for a certain version is simpler (it’s just one string instead of a JSON object composed of type and version(s)). Updating the version in the client metadata is required anyway since this is an important piece of information with respect to the client‘s expectations towards the AS.

**Comment by vdzhuvinov** [comment]
Today we managed to come up with some nice heuristic to find out if a type has a version encoded and then extract the value, sparing the need for an additional config, so given that and the implications for metadata the separate version field is beginning to look like a horrible idea :)

**Comment by tlodderstedt** [comment]
Mind to share the heuristic? 

Shall I close the ticket?

**Comment by vdzhuvinov** [comment]
The heuristic we're looking at is this: if there are two (or more) persisted consents where the type matches up to a string at the end which resembles a version number (allowed 0_9, dots), then those types are assumed to be versions of the same type. The versions are then sorted according to their numbering to determine their order.

Yes, I think the ticket can be closed now. Thanks!
