### ISSUE TITLE
Unknown parameters in a authorization_details -> type object

### ISSUE THREAD

**Issue by vdzhuvinov** [oauthstuff/draft-oauth-rar#45]
Let's suppose the AS doesn't validate the authz details JSON object against a schema, but simply parses it into a form or application object. If there are any unknown parameters in the JSON object - should the AS ignore them or return an invalid_request error?

**Comment by jricher** [comment]
I think that might be under the control of the "type" parameter's definition, since it controls the namespace. I can imagine some spaces that would want to have greater flexibility and ignore unknown values, and those that want to be strict. You don't need to check against a formal schema to apply rules like that.

More important is what the AS does if it sees a `type` value it doesn't understand. I think that SHOULD be a rejection. However, what does it even mean for the AS to "understand" a type value? Some general purpose AS is going to just process everything and let the RS do the enforcement by exposing the actual values to it via token or introspection.

**Comment by vdzhuvinov** [comment]
Thanks, that was useful. The RS doing the ultimate check - we didn't think about that.

**Comment by tlodderstedt** [comment]
I would assume even a general purpose AS needs to be aware of rules how to handle certain authorization_details types, simply because it needs to render meaningful user consent or determine the authorization of the client for a certain type of access.

Just passing the authorization_details object through to the RS (actually what RS in a multi RS setup?) won't work in my opinion.

**Comment by tlodderstedt** [comment]
I see several ways to handle unknown elements in an authz details type:
- the AS ignores the element but retains it in the authorization details object (might be a useful extension point but also smells a bit like injection)
- the AS omits this element in the authorization details (might lead to unexpected behavior if the client does not fully inspect the authz details parameter in the token response)
- the AS rejects a request containing an authz details object it does not fully understand

If we would conduct this discussion for scope values, I think we would go with the 3rd approach. I'm leaning towards robustness and would suggest to make this an error condition. 

Please have a look at PR #59 .
