### ISSUE TITLE
AS initiated actions

### ISSUE THREAD

**Issue by matdehaast** [oauthstuff/draft-oauth-rar#46]
This has been on my mind and I see David Waite also brought it up in the recent Meeting Minutes. Does RAR allow for AS initiated actions?

> To stick with the primary payment example - there are payment cases which model well for single resource authorization, such as a PayPal-style transaction where the client is also the recipient of funds. For other types of transactions, I would worry this may become primarily an AS-executed action rather than a client authorization.

An example is that as a business I direct a consumer to pay an invoice, so I submit the invoice along with AS request. Could the auth flow actually initiate the action at the end of the flow automatically and pay the invoice?

I personally don't like or think the AS should be able to initiate actions as it breaks the separation of concern but I could see how it could simplify API's that wish to perform an action based on the result of Auth.

**Comment by tlodderstedt** [comment]
I don't see this in scope of RAR as I think the client should initiate/request actions directly with the respective API. This allows the client to control order of actions and error handling. If the AS would initiate actions, the protocol would be overloaded with API-specific response and error data. Moreover, it would increase the AS's complexity. 

The focus of RAR is on defining a **standard** for more detailed authorization requests. I say **standard**, since this kind of authorization process is already happening (including the impact on AS processing DW mentioned) in the context of open banking but different APIs use very different ways to convey the authorization data.

**Comment by matdehaast** [comment]
Thanks I agree 100% with that sentiment.
