### ISSUE TITLE
Differentiate between authorization_details bound to access token and grant/refresh token

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#48]
I think the token response should be defined to return both, the authorization details of the grant and the authorization details bound to the issued access token - if both are different. 

In case the AS issues RS-specific access tokens, the AS must otherwise either return a sub set of authorization details and the client will never learn the full "scope" of authorization details the user consented with or the AS returns the full set of authorization details but the client does not know which sub set os applicable to the current access token. 

BTW: we should have specified the same for scope long time ago.

**Comment by jricher** [comment]
I think we're a bit stuck with the OAuth 2 access token model, where the token response is all about the access token and the refresh token is an also-present value within that. There's not an easy way to fix this without changing that. 

In XYZ, I have been internally modeling it as the transaction having its set of `resources`, which lives at the root, and the access token potentially having its own set of `resources` specific to that access token. There isn't a separate refresh token artifact so much as continuing the transaction itself once it's been approved. Since the transaction can be continued and up/down scoped, it makes more sense to have them separate.

**Comment by b---c** [comment]
There is some awkwardness around how OAuth 2 handled this (or didn't really handle it) for scope. But that doesn't prevent RAR from endeavoring to address it. As an extension of OAuth 2 it can add parameters to the token response that are defined as need be. So there could be an `at_authz_deets` and a `grant_authz_deets` (or similar but with better names) that allow for the distinction. 

In practice, it's only actually an issue with the code exchange, right? Like when the user authorizes a broad set of stuff for the grant at the UI from the authz endpoint but the client wants to downscope the AT it gets from the initial code exchange but still get the RT with the full granted access.

**Comment by tlodderstedt** [comment]
> In practice, it's only actually an issue with the code exchange, right? Like when the user authorizes a broad set of stuff for the grant at the UI from the authz endpoint but the client wants to downscope the AT it gets from the initial code exchange but still get the RT with the full granted access.

Authz code and refresh token grnánt types, which makes me think this might be more related to refresh tokens being issued at the token endpoint than the particular grant type.  So `rt_authz_deets` might be more appropriate.

**Comment by tlodderstedt** [comment]
see #54
