### ISSUE TITLE
authorization_details token response parameter

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#54]
Does this parameter specify the authorization details assigned to the access token or the overall grant (potentially represented by a refresh token)?

Do we need both perspectives?

**Comment by jricher** [comment]
Since OAuth doesn't separate the two, I think we should take the same approach as scope, where the field signifies the scope for the access token, but also the overall request (and refresh token) in responses for non-refresh grants. It's unclear and confusing but at least marginally consistent without redefining OAuth's response model.

**Comment by tlodderstedt** [comment]
ok. we will leave the text as is.
