### ISSUE TITLE
Make scopes and authorization details Mutual exclusive for particular RS?

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-rar#62]
This came up in a discussion with Filip Skokan. I don’t see any reason to allow clients to ask for access to a certain RS/API using different mechanisms. Our experience in the yes ecosystem suggest, one will either need the expressiveness or RAR (and cannot use scopes) or not. So I would be fine with such a change assuming it makes implementer life easier.

**Comment by leastprivilege** [comment]
IRL - it seems unlikely that a RS would be able to handle both scope and authorization details. But this is probably very deployment specific.

**Comment by panva** [comment]
I'm supportive of this, but you have to consider RAR must be usable in conjunction with OIDC which requires the scope `openid` to be present. So it will require some creative thinking and normative language to express such constrain while not stamping on OIDC.

**Comment by tlodderstedt** [comment]
Using scope openid to control the behavior of the OpenID Connect API and an authorization detail, let’s say account_information, for another API would work with this proposal even if scope openid and the authorization detail is passed within the same authorization request.

The AS will need to relate the respective artifacts to the respective service, i.e. scope for service OpenID Connect and authorization detail account_information for the account information API.

We do similar things now with OpenID Connect and electronic signing (where we use RAR).

**Comment by bc-pi** [comment]
> I don’t see any reason to allow clients to ask for access to a certain RS/API using different mechanisms.

I'm not sure how you'd disallow it though.

**Comment by jricher** [comment]
I'm a little confused as to the proposal here, and I'm wondering which way I should read what's being suggested:

1) The client will not be allowed to send both `scope` and `authorization_details` in a single request
2) The definition of a `scope` value is independent of an `authorization_details` value to the extent that they can never apply to the same RS
3) Something else?

I don't particularly care for (1) or (2) above. (1) falls apart for the reasons suggested above. (2) starts to fail because the definition of "a single RS" is really loose in the OAuth world, to the point where one "RS" could host multiple APIs, depending on how you look at it. Additionally, this model would be equivalent to saying that some combinations of scopes or some combinations of RAR objects are forbidden. 

Ultimately the access token is the sum of everything being requested. I think we can potentially be more clear about that relationship, and that the interaction between access requests defined by scope and by RAR are up to the AS/RS to define. This is the same reason I'm not a fan of us defining how `locations` and `resource` fit together, but that makes slightly more sense to me at least.

**Comment by vdzhuvinov** [comment]
This is good point to consider when designing the access for an API or upgrading an existing scopes based access with RAR.
Let's not however make it normative, for all the good reasons mentioned above.

**Comment by tlodderstedt** [comment]
close this ticket as consensus seems o not make i a normative requirement
