### ISSUE TITLE
the introspection response and self contained ATs

### ISSUE THREAD

**Issue by adeinega** [oauthstuff/draft-oauth-rar#86]
Shouldn't it matter which type of ATs are being introspected, I meanm opaque vs self-contained vs any other type?

At this moment the specification uses

> In the case of opaque access tokens, the data provided to a certain RS is

what if an RS doesn't know or simply doesn't have the means to verify/work with JWT ATs?

**Comment by tlodderstedt** [comment]
The format doesn't matter to the RS in case of opaque token since the RS just sends the token to the AS's introspection endpoint.
I don't get the meaning of "what if an RS doesn't know or simply doesn't have the means to verify/work with JWT ATs?" The token format is subject to the "contract" between AS and RS. The AS should know what tokens to issue for a certain RS. So if AS and RS came to the agreement to use self-contained JWTs, the RS must process them. If the come to the agreement to use opaque tokens, the AS can issue tokens in the format it needs.

**Comment by jricher** [comment]
I think I understand the question that @adeinega is asking here, so let me try to rephrase:

Isn't it the case that an RS could just as easily introspect a token that's self-contained, like a JWT?

And in that sense, I think that the following intro sentence to section 9.2 is confusing:

> In the case of opaque access tokens, the data provided to a certain RS is determined using the RS's identifier with the AS (see [[I-D.ietf-oauth-jwt-introspection-response](https://www.ietf.org/archive/id/draft-ietf-oauth-rar-11.html#I-D.ietf-oauth-jwt-introspection-response)], section 3).

Reading it again now, I'm not sure what it has to do with RAR. I suggest we drop that sentence and replace it: #87
